-- Creating tables for Fantasy Data
CREATE TABLE fantasy (
	Player VARCHAR(22) NOT NULL,
	Tm VARCHAR(3) NOT NULL,
	Pos VARCHAR(2) NOT NULL,
	Age INT NOT NULL,
	"G" INT NOT NULL,
	GS INT NOT NULL,
	PlID VARCHAR(26) NOT NULL,
	TmID VARCHAR(7) NOT NULL,
	Cmp_G FLOAT NOT NULL,
	PassAtt_G FLOAT NOT NULL,
	PassYds_G FLOAT NOT NULL,
	PassTD_G FLOAT NOT NULL,
	Int_G FLOAT NOT NULL,
	RushAtt_G FLOAT NOT NULL,
	RushYds_G FLOAT NOT NULL,
	RushYds_Att FLOAT NOT NULL,
	RushTD_G FLOAT NOT NULL,
	Tgt_G FLOAT NOT NULL,
	Rec_G FLOAT NOT NULL,
	RecYds_G FLOAT NOT NULL,
	Yds_Rec FLOAT NOT NULL,
	RecTD_G FLOAT NOT NULL,
	Fmb_G FLOAT NOT NULL,
	FL_G FLOAT NOT NULL,
	TotTD_G FLOAT NOT NULL,
	"2PM_G" FLOAT NOT NULL,
	"2PP_G" FLOAT NOT NULL,
	FPts FLOAT NOT NULL,
	PosRk INT NOT NULL,
	OvRank INT NOT NULL,
	Yr INT NOT NULL,
	PPR_G FLOAT NOT NULL,
	Starter INT NOT NULL,
	Next_Yr_PPG FLOAT,
	Next_Yr_Starter FLOAT,
	PRIMARY KEY (PlID, TmID)
);

CREATE TABLE teams (
	Tm VARCHAR(24) NOT NULL,
	Abbr VARCHAR(3) NOT NULL,
	"G" INT NOT NULL,
	PF_G FLOAT NOT NULL,
	TotYds_G FLOAT NOT NULL,
	Ply_G FLOAT NOT NULL,
	Yds_Play FLOAT NOT NULL,
	TO_G FLOAT NOT NULL,
	FL_G FLOAT NOT NULL,
	"1stD_G" FLOAT NOT NULL,
	Cmp_G FLOAT NOT NULL,
	PasAtt_G FLOAT NOT NULL,
	"Comp%" FLOAT(4) NOT NULL,
	PassYds_G FLOAT NOT NULL,
	PassTD_G FLOAT NOT NULL,
	"PassTD%" FLOAT(4) NOT NULL,
	Int_G FLOAT NOT NULL,
	"INT%" FLOAT(4) NOT NULL,
	NY_PassA FLOAT NOT NULL,
	Pass1stD_G FLOAT NOT NULL,
	PassLong INT NOT NULL,
	Yds_PassA FLOAT NOT NULL,
	AYds_PassA FLOAT NOT NULL,
	Y_Comp FLOAT NOT NULL,
	PassRate FLOAT NOT NULL,
	Sk_G FLOAT NOT NULL,
	SackYds_G FLOAT NOT NULL,
	"Sack%" FLOAT(4) NOT NULL,
	ANY_PA FLOAT NOT NULL,
	"4QComeB" INT NOT NULL,
	GWinDri INT NOT NULL,
	EXPPass_G FLOAT NOT NULL,
	RushAtt_G FLOAT NOT NULL,
	RushYds_G FLOAT NOT NULL,
	RushTDs_G FLOAT NOT NULL,
	RLong INT NOT NULL,
	Yds_RA FLOAT NOT NULL,
	Rush1stD_G FLOAT NOT NULL,
	Fmb_G FLOAT NOT NULL,
	EXPRush_G FLOAT NOT NULL,
	Pen_G FLOAT NOT NULL,
	PenYds_G FLOAT NOT NULL,
	"1stPy_G" FLOAT NOT NULL,
	"Score%" FLOAT(4) NOT NULL,
	"TurnOv%" FLOAT(4) NOT NULL,
	EXPTot_G FLOAT NOT NULL,
	"Year" INT NOT NULL,
	TmID VARCHAR(7) NOT NULL,
	PRIMARY KEY (TmID)
);

CREATE TABLE advPass (
	Player VARCHAR(20) NOT NULL,
	Tm VARCHAR(3) NOT NULL,
	Pos VARCHAR(3) NOT NULL,
	Age INT NOT NULL,
	"G" INT NOT NULL,
	GS INT NOT NULL,
	Cmp_G FLOAT NOT NULL,
	Att_G FLOAT NOT NULL,
	Yds_G FLOAT NOT NULL,
	IAY_G FLOAT NOT NULL,
	IAirYds_Pass FLOAT NOT NULL,
	CAY_G FLOAT NOT NULL,
	CAirYds_Cmp FLOAT NOT NULL,
	CAirYds_Pass FLOAT NOT NULL,
	YAC_G FLOAT NOT NULL,
	YdsAC_Cmp FLOAT NOT NULL,
	Bats_G FLOAT NOT NULL,
	ThAwy_G FLOAT NOT NULL,
	Spikes_G FLOAT NOT NULL,
	Drops_G FLOAT NOT NULL,
	"Drp%" FLOAT(4) NOT NULL,
	BadTh_G FLOAT NOT NULL,
	"BadTh%" FLOAT(4) NOT NULL,
	OnTgt_G FLOAT NOT NULL,
	"OnTarg%" FLOAT(4) NOT NULL,
	Sk_G FLOAT NOT NULL,
	PockTime FLOAT NOT NULL,
	Bltz_G FLOAT NOT NULL,
	Hrry_G FLOAT NOT NULL,
	Prss_G FLOAT NOT NULL,
	"Press%" FLOAT(4) NOT NULL,
	Scrm_G FLOAT NOT NULL,
	Yds_Scram FLOAT NOT NULL,
	Plays_G FLOAT NOT NULL,
	RPO_Yds_G FLOAT NOT NULL,
	RPO_PassAtt_G FLOAT NOT NULL,
	RPO_PassYds_G FLOAT NOT NULL,
	RPO_RushAtt_G FLOAT NOT NULL,
	RPO_RushYds_G FLOAT NOT NULL,
	PA_PassAtt_G FLOAT NOT NULL,
	PA_PassYds_G FLOAT NOT NULL,
	"Year" INT NOT NULL,
	PlID VARCHAR(24) NOT NULL,
	TmID VARCHAR(7) NOT NULL,
	PRIMARY KEY (PlID, TmID)
);

CREATE TABLE advRush (
	Player VARCHAR(22) NOT NULL,
	Tm VARCHAR(3) NOT NULL,
	Pos VARCHAR(3) NOT NULL,
	Age INT NOT NULL,
	"G" INT NOT NULL,
	GS INT NOT NULL,
	Att_G FLOAT NOT NULL,
	Yds_G FLOAT NOT NULL,
	"1D_G" FLOAT NOT NULL,
	YBC_G FLOAT NOT NULL,
	YBCont_A FLOAT NOT NULL,
	YAC_G FLOAT NOT NULL,
	YACont_A FLOAT NOT NULL,
	BrkTkl_G FLOAT NOT NULL,
	Att_BrTk FLOAT NOT NULL,
	"Year" INT NOT NULL,
	PlID VARCHAR(26) NOT NULL,
	TmID VARCHAR(7) NOT NULL,
	PRIMARY KEY (PlID, TmID)
);

CREATE TABLE advRec (
	Player VARCHAR(22) NOT NULL,
	Tm VARCHAR(3) NOT NULL,
	Pos VARCHAR(3) NOT NULL,
	Age INT NOT NULL,
	"G" INT NOT NULL,
	GS INT NOT NULL,
	Tgt_G FLOAT NOT NULL,
	Rec_G FLOAT NOT NULL,
	Yds_G FLOAT NOT NULL,
	TD_G FLOAT NOT NULL,
	"1D_G" FLOAT NOT NULL,
	YBC_G FLOAT NOT NULL,
	YdsBC_Rec FLOAT NOT NULL,
	YAC_G FLOAT NOT NULL,
	YdsAC_Rec FLOAT NOT NULL,
	AvgDOT FLOAT NOT NULL,
	BrkTkl_G FLOAT NOT NULL,
	Rec_BrTk FLOAT NOT NULL,
	Drop_G FLOAT NOT NULL,
	"Drp%" FLOAT(4) NOT NULL,
	Int_G FLOAT NOT NULL,
	PassRat FLOAT NOT NULL,
	"Year" INT NOT NULL,
	PlID VARCHAR(26) NOT NULL,
	TmID VARCHAR(7) NOT NULL,
	PRIMARY KEY (PlID, TmID)
);

CREATE TABLE passerratings (
	Player VARCHAR(17) NOT NULL,
	Team VARCHAR(3) NOT NULL,
	Cmp INT NOT NULL,
	Att INT NOT NULL,
	Yds INT NOT NULL,
	TD INT NOT NULL,
	"Int" INT NOT NULL,
	AvgRate FLOAT(4) NOT NULL,
	PassRate FLOAT(2) NOT NULL,
	"Year" INT NOT NULL,
	PlID VARCHAR(21) NOT NULL,
	PRIMARY KEY (PlID)
);

CREATE TABLE starters (
	Starter VARCHAR(17) NOT NULL,
	Tm VARCHAR(3) NOT NULL,
	"Year" INT NOT NULL,
	PlID VARCHAR(21) NOT NULL,
	TmID VARCHAR(7) NOT NULL,
	PRIMARY KEY (PlID, TMID)
);

SELECT * 
FROM teams;

SELECT *
FROM fantasy;

SELECT *
FROM advpass;

SELECT *
FROM advrush;

SELECT *
FROM advrec;

SELECT *
FROM passerratings;

SELECT *
FROM starters;